# Offense count: 13
Metrics/AbcSize:
  Max: 28

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 122

# Offense count: 2
Metrics/CyclomaticComplexity:
  Max: 7

# Offense count: 112
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 177

# Offense count: 16
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 23

# Offense count: 3
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 3
# Configuration parameters: Include.
Rails/Validation:
  Enabled: false

# Offense count: 5
Style/AccessorMethodName:
  Enabled: false

# Offense count: 35
Style/AsciiComments:
  Enabled: false

# Offense count: 8
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 1
Style/ClassVars:
  Enabled: false

# Offense count: 64
Style/Documentation:
  Enabled: false

# Offense count: 3
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false