inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true

  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - Gemfile
    - Guardfile
    - app/helpers/items_helper.rb
    - local/**/*

Lint/EndAlignment:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes